### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by knathan1987** [9a4gl/py-centrometal-web-boiler#1]
Hi!
This is not really an issue. Just some questions 😉

I'm currently looking to replace my current Boiler - and the Centrometal ones got my interest. BUT: I don't want to rely the WiFi functionality on any external servers, since we never know how long they will support them.

So... Since you already have one of those - here are some questions:
1.) Does the Wifi-Module have any built-in web server? Maybe on some non-standard Port (port scan?)

2.) Have you tried to reverse-engineer the communication with the external server? (Maybe by adding some nameserver entries and redirect the connection to a Raspberry Pi or something)

3.) Could you post a Picture of the WiFi-PCB? Would be nice to know what Controller they used - maybe it would be possible to modify that firmware 😊

Thank you very much in advance!

**Comment by 9a4gl** [comment]
1) no as far as I know
2) it is ESP32 board connecting to their MQTT server in the cloud, I tried to montor (with Wiresshark) messages to their mqtt server, commnication is unecritped (so far) and you can see the messages, the problem is that each message has signature.
I have not tried, but with DNS or firewall you can redirect to your MQTT server, maybe you can listen, but as each message has signature I am pretty sure it will not reach to command (power on/off)
3) I had idea to buy another one and sacrefice it for science, but after realizing each mqtt message has signature I think the whole work will be useless :( So I decided to login to their web app and get data there, and is easier for other users. Redirecting to own mqtt is not everyone knows how to do.
BR, Tihomir

**Comment by knathan1987** [comment]
Wow! Thanks for your fast reply.

ESP32 & MQTT sounds pretty good. Hopefully the flash is not encrypted. Maybe the ESP is even using micropython, LUA or some other script interpreter. If so, it should be really easy to determine the signature algorithm and how (if?) the signature is verified.

Anyway... Thank you very much!
I think I will buy a WiFi module and try to access the flash content.....

**Comment by 9a4gl** [comment]
You sound optimistic, if I would be releasing such device I would make sure you do not successed :) That is why I gave up. Note that signature is maybe generated in the boiler, not in the wifibox. 
Maybe there is easier approach, wifibox is communicating with the boiler probably using serial port and maybe that can be intercepted, but not is a lot of work, which I wanted to avoid, and again, not acceptable my most of users.
Note the boiler sends cca 100 entities and it is very cryptic and hard to find what means what. Web application actually helps here a lot.
Let me know what you find. Good luck.

**Comment by zux500** [comment]
Hey @knathan1987, did you have any luck investigating this further?
I hate the fact that it uses wifi and external server for control.
Would love to switch to cable and control locally.
